# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Europe Rail Road (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Europe Rail Road (iOS)

  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'

end

target 'Europe Rail Road (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Europe Rail Road (macOS)

end
